---
- hosts: production_servers
  gather_facts: true
  remote_user: ubuntu
  sudo: yes
  vars:
    target_home: /home/ubuntu
  tasks:
  - name: Add Postgres Repo
    apt_repository: repo='deb https://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main'
  - name: Install Postgres Certs
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  - name: Add Elastic Search Repo
    apt_repository: repo='deb http://packages.elastic.co/elasticsearch/2.x/debian stable main'
  - name: Install ElasticSearch Certs
    apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch
  - name: Add software-properties-common
    apt: name=software-properties-common state=present
  - name: Add Haskell Repo
    apt_repository: repo='ppa:hvr/ghc' state=present
  - name: Upgrade apt
    apt: update_cache=yes upgrade=yes
  - name: Install deps
    apt: name={{ item }} state=present
    with_items:
    - elasticsearch
    - git
    - postgresql-9.4
    - openjdk-7-jre
  - name: Start ElasticSearch daemon
    service: name=elasticsearch state=started
  - name: Install GHC
    apt: name=ghc-7.10.3 state=present
  - name: Install Cabal
    apt: name=cabal-install-1.22 state=present
  - name: Symlink cabal
    file: path=/usr/bin/cabal src=/usr/bin/cabal-1.22 state=link
  - name: Append to .bashrc
    lineinfile:
      dest={{target_home}}/.bashrc
      line='export PATH="$HOME/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:$PATH"'
      insertafter=EOF
      state=present
  - name: Update Cabal
    sudo: no
    command: cabal update
  - name: Use Cabal to install Cabal Install so we can install... what again?
    sudo: no
    command: cabal install cabal-install

  # downloadin da softwares
  - name: Download Feature Creature
    sudo: no
    git:
      repo=git@github.com:gust/feature-creature.git
      dest={{target_home}}/feature-creature
      accept_hostkey=yes
  - name: Create Cabal Sandbox
    sudo: no
    command: cabal sandbox init
    args:
      chdir: "{{target_home}}/feature-creature"
  - name: Build API From Source
    sudo: no
    command: cabal install
    args:
      chdir: "{{target_home}}/feature-creature"
